apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-grading
  namespace: argocd
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/Duong-Vu-practice-workspace/web-programming-grading-config-test1.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
        - values-stg.yaml
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: web-grading
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
