#!/usr/bin/env bash
set -euo pipefail

echo "=== Hướng dẫn thêm service mới ==="
echo ""
echo "Để thêm 1 service mới vào ArgoCD, làm theo các bước sau:"
echo ""
echo " 1. Thêm entry vào deploy/helm/web-grading/values.yaml dưới section services:"
echo "    services:"
echo "      - name: <service-name>"
echo "        image: <image>"
echo "        port: <port>"
echo ""
echo " 2. Thêm route cho service trong deploy/cloudflared/config.yml"
echo ""
echo " 3. Push code lên GitHub, ArgoCD tự sync"
echo ""
echo "=== Các service hiện tại ==="
echo " - web-grading-api"
echo " - web-grading-executor"
echo ""
echo "=== Observability ==="
echo " Deploy stack: bash deploy/observability/deploy.sh"
echo " Grafana:      NodePort 30300 (admin/admin)"
echo " Datasources:  Prometheus, Loki, Tempo"
